### PR TITLE
update hazelcast to 3.9 and add hz-list to retrieve a list from hazelcast

### PR DESCRIPTION
**Pull request by hellonico**

### CODE REVIEW

**Comment by tolitius** [comment]
thanks for PR. A couple of comments:

* `pom {:project     'hellonico/chazel'..}` [here](https://github.com/hellonico/chazel/blob/master/build.boot#L49) is probably a commit mistake

* why to `3.9` and not to `3.9.2`?

I [did](https://github.com/tolitius/chazel/commit/a578c29dcf9cac4b9970cc937df68fee9d42062f) update `chazel` to `3.9.2` before, the reason I reverted back to `3.8.9` is because `3.9+` did not work (was very slow) in a couple of production clusters. Are there any particular features you are missing in `3.8.9`?

**Comment by hellonico** [comment]
- yes, the pom was for me to deploy the jar on my nexus repo. Sorry for the project name change.

- I am actually using jet, coupled with hazelcast+chazel, and anything depending on hazelcast 3.8* seems to get the jet jobs to fail. I get the jet exception below when running a distributed job:

Exception in thread "hz._hzInstance_1_jet.cached.thread-4" java.lang.NoSuchMethodError: com.hazelcast.internal.partition.impl.InternalPartitionServiceImpl.isMigrationAllowed()Z
	at com.hazelcast.jet.impl.JobCoordinationService.shouldStartJobs(JobCoordinationService.java:551)
	at com.hazelcast.jet.impl.JobCoordinationService.scanJobs(JobCoordinationService.java:600)
	at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:66)
	at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227)

... hence the update to something in the 3.9 series. 
I just realized today [3.9.3](http://mvnrepository.com/artifact/com.hazelcast/hazelcast) was out , tried with that version and things worked smoothly when submitting jet jobs.

**Comment by tolitius** [comment]
sounds good, just fix the pom property and update hz to `3.9.3` I'll merge the pull request

**Comment by hellonico** [comment]
done !

**Comment by tolitius** [comment]
thank you

**Pull request merged**
